server:
  port: 8081

jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supportportal #change this to your database url
    password: letmein #change this to your database username
    username: root #change this to your database password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

